name: campus_mobile_experimental
description: Mobile app platform for campus.
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  app_settings: 4.1.0
  background_fetch: 0.7.2
  barcode_widget: 2.0.1
  beacon_broadcast: 0.2.3
  device_info: 2.0.0
  dio: 4.0.0
  dots_indicator: 2.0.0
  encrypt: 5.0.0
  firebase_analytics: 7.1.1
  firebase_core: 1.0.3
  firebase_crashlytics: 2.0.0
  firebase_messaging: 9.1.1
  flutter:
    sdk: flutter
  flutter_scandit_plugin: 1.1.0 # Upgrade https://github.com/UCSD/flutter_scandit.git
  flutter_blue:
    git:
      url: https://github.com/UCSD/flutter_blue.git
      ref: master
  flutter_linkify: 5.0.2
  flutter_secure_storage: 4.1.0
  flutter_sticky_header: 0.6.0
  google_maps_flutter: 2.0.3
  hive: 2.0.3
  hive_flutter: 1.0.0
  intl: 0.17.0
  location: 4.1.1
  package_info: 2.0.0
  pointycastle: 3.0.1
  provider: 5.0.0
  shared_preferences: 2.0.5
  url_launcher: 6.0.3
  uuid: 3.0.4
  permission_handler: 6.1.1
  webview_flutter: 2.0.4
  uni_links2: 0.6.0+2
dev_dependencies:
  build_runner: # https://github.com/hivedb/hive/issues/605
  flutter_test:
    sdk: flutter
  hive_generator: # https://github.com/hivedb/hive/issues/605
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/public_key.txt