name: campus_mobile_experimental
description: A new Flutter project.
version: 7.2.13+844

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  app_settings: 4.0.4
  auto_size_text: 2.1.0
  background_fetch: 0.6.0
  barcode_scan: 3.0.1
  barcode_widget: 1.3.0
  beacon_broadcast: 0.2.1
  cached_network_image: 1.1.2+1
  device_info: 0.4.2+2
  dio: 3.0.7
  dots_indicator: 1.2.0
  encrypt: 3.2.0
  firebase_analytics: 5.0.2
  firebase_core: 0.4.4
  firebase_crashlytics: 0.1.3+3
  firebase_messaging: 6.0.13
  flutter_blue:
    git:
      url: https://github.com/UCSD/flutter_blue.git
      ref: master
  flutter_linkify: 3.1.3            # TEST
  flutter_secure_storage: 3.3.1+1
  flutter_sticky_header: 0.4.0
  flutter:
    sdk: flutter
  google_maps_flutter: 0.5.28+1
  hive_flutter: 0.3.1
  hive: 1.4.2
  intl: 0.16.0
  location: 3.0.2
  package_info: 0.4.0+18
  path_provider: 1.6.8
  pointycastle: 1.0.1
  provider: 4.0.5
  shared_preferences: 0.5.6+3
  url_launcher: 5.2.5
  uuid: 2.2.0
  webview_flutter:
    git:
      path: packages/webview_flutter
      ref: webview-transparent-background
      url: "git://github.com/crizant/plugins"

dev_dependencies:
  hive_generator: 0.7.1
  build_runner: 1.8.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/public_key.txt